import styled from '@emotion/styled'
import { AppTheme } from 'src/ui-data/theme/AppTheme.ts'
import { LightProps } from 'src/ui-data/theme/themes/Light.ts'
import Theme = AppTheme.Theme
import themeIconCss = AppTheme.themeIconCss
import ThemeProps = AppTheme.ThemeProps




export const LightBurgundyProps: ThemeProps = { ...LightProps,
  
  page: { ...LightProps.page,
    bg:         ['#f5f5f5'],
    bgGradient: ['#f5f5f5', '#f5f5f5', '#f5f5f5'],
  },
  statusBar: { ...LightProps.statusBar,
    bg: ['#ffffff'],
  },
  nav: { ...LightProps.nav,
    bg: ['#ffffff'],
  },
  navButton: { ...LightProps.navButton,
    bgFocus:      ['#f0f0f0'],
    content:       ['#7b7b7b'],
    contentAccent: ['#BB2649'],
  },
  
  containerNormal: { ...LightProps.containerNormal,
    bg:       ['#ffffff'],
    bg2:      ['#f0f0f0'],
    content:   ['#000000'],
    content2:  ['#555555'],
    content3:  ['#7b7b7b'],
    contentAccent:    ['#ffdde5'],
    contentAccent2:   ['#F75F82'],
    contentAccent3:   ['#BB2649'],
  },
  containerAccent: { ...LightProps.containerAccent,
    bg:       ['#bbbbbb'],
    bg2:      ['#F75F82'],
    bg3:      '#F07E98',
    content:  ['#000000'],
    content2: ['#F8F8F8'],
    c3:       '#ffffff',
  },
  
  buttonMain: { ...LightProps.buttonMain,
    bg:       ['#F75F82'],
    bgFocus:  ['#ff537a'],
    content:   ['#ffffff'],
  },
  buttonAccent: { ...LightProps.buttonAccent,
    bg:            ['#F75F82'],
    bg2:           ['#F07E98'],
    content:       ['#ffffff'],
    bgFocus:       ['#ff537a'],
    contentFocus:  ['#ffffff'],
  },
  buttonNormal: { ...LightProps.buttonNormal,
    bg:           ['#bbbbbb'],
    content:       ['#000000'],
    bgFocus:      ['#dddddd'],
    contentFocus:  ['#000000'],
  },
  buttonSecondary: { ...LightProps.buttonSecondary,
    bg:       ['transparent'],
    bgFocus:  ['#99999988'],
    content:   ['#bbbbbb'],
  },
  inputRadio: { ...LightProps.inputRadio,
    bgFocus:  ['#7b7b7b'],
  },
  buttonTransparent: { ...LightProps.buttonTransparent,
    bgFocus: ['#00000011'],
  },
  
  iconGradient: { ...LightProps.iconGradient,
    content:       ['#BB2649', '#F75F82'],
  },
  
  input: { ...LightProps.input,
    bg:           ['#F8F8F8'],
    content:       ['#000000'],
    placeholder:   ['#777777'],
    border:        ['#7b7b7b', '#7b7b7b'],
    borderHover:   ['#7b7b7b'],
    bgError:      ['#ffced2'], //['#ff8787'],
  },
  
  rangePicker: { ...LightProps.rangePicker,
    trackBg:      ['#ffdde5'],
    barBg:        ['#F75F82'],
    handleBg:     ['#F8F8F8'],
  },
  
  elementDisabled: { ...LightProps.elementDisabled,
    bg:     ['#DCDCDC'],
    content: ['#555555'],
  },
  elementDanger: { ...LightProps.elementDanger,
    bg:      ['#7b7b7b'],
    bgFocus: ['#999999'],
    content:  ['#ffffff'],
  },
  elementError: { ...LightProps.elementError,
    bg:      ['#ffced2'],
  },
  
  ripple: { ...LightProps.ripple,
    content:              ['#ffffff'],
    contentOnTransparent: ['#666666'],
  },
  
  photos: { ...LightProps.photos,
    bg:                     ['#ffeeee'],
    content:                 ['#291f1d'],
    borderDrag:              ['#1F8DCD'],
    highlightFrameBg:       ['#8B8B8B'],
    highlightFrameAccentBg: ['#ffbaba'],
  },
  
  bottomSheet: { ...LightProps.bottomSheet,
    bg:    ['#ffffff'],
    handle: ['#8b8b8b'],
  },
  
  toast: { ...LightProps.toast,
    bg:                  ['#ffffff'],
    content:              ['#757575'],
    content2:             ['#b2b2b2'],
    content3:             ['#000000'],
    accentNormal:         ['#bb86fc'],
    accentLoadingBg:     ['#e0e0e0'],
    accentLoadingContent: ['#616161'],
    accentInfo:           ['#3498db'],
    accentOk:             ['#07bc0c'],
    accentWarn:           ['#f1c40f'],
    accentDanger:         ['#e74c3c'],
  },
  scrollbar: { ...LightProps.scrollbar,
    track:       ['#25283622'],
    thumb:       ['#25283644'],
    thumbActive: ['#999999'],
  },
}



export const LightBurgundy = {
  ...LightBurgundyProps,
  type: 'light',
  name: 'Light Burgundy' as const,
  icon: styled.div(themeIconCss({
    accentColor: LightBurgundyProps.containerNormal.contentAccent3[0],
    bgColor1:   LightBurgundyProps.containerNormal.contentAccent2[0],
    bgColor2:   LightBurgundyProps.page.bg[0],
  })),
} satisfies Theme

