import { SwChannel } from '@utils/service-worker/SwChannel.ts'
import { getIsSwReady } from '@utils/service-worker/SwU.ts'
import { WsMsg } from '@utils/web-socket/WsU.ts'
import React, { useEffect } from 'react'
import { useAppZustand } from 'src/zustand/app/appZustand.ts'





const SwListener = React.memo(() => {
  
  useEffect(() => {
    const onMsg = (msg?: WsMsg) => {
      console.log('SwListener received:', msg)
      const { type: t, data } = msg ?? { }
      
      /*
      if (t === 'SW_READY') {
        useAppZustand.setState({ swReady: getIsSwReady() })
      }
      else if (t === 'SW_NOT_READY') {
        useAppZustand.setState({ swReady: false })
      }
      */
    }
    
    SwChannel.addOnMsgListener(onMsg)
    return () => SwChannel.removeOnMsgListener(onMsg)
  }, [])
  
  useEffect(() => {
    console.log('SwListener getIsSwReady()', getIsSwReady())
    useAppZustand.setState({ swReady: getIsSwReady() })
    const onControllerChange = () => {
      console.log('SwListener onControllerChange', getIsSwReady())
      useAppZustand.setState({ swReady: true })
    }
    navigator.serviceWorker.addEventListener('controllerchange', onControllerChange)
    return () => navigator.serviceWorker.removeEventListener('controllerchange', onControllerChange)
  }, [])
  
  return undefined
})
SwListener.displayName = 'SwListener'
export default SwListener



// TODO Push Notifications through SW
async function f() {
  const readySw = await navigator.serviceWorker.ready
  readySw.addEventListener('updatefound', ev => {
  
  })
  const registration = await navigator.serviceWorker.ready
  const subscription = await registration.pushManager.getSubscription()
  subscription?.unsubscribe()
}

// This function is needed because Chrome doesn't accept a base64 encoded string
// as value for applicationServerKey in pushManager.subscribe yet
// https://bugs.chromium.org/p/chromium/issues/detail?id=802280
function urlBase64ToUint8Array(base64String: string) {
  const padding = '='.repeat((4 - base64String.length % 4) % 4)
  const base64 = (base64String + padding)
    .replace(/-/g, '+')
    .replace(/_/g, '/')
  
  const rawData = window.atob(base64)
  const outputArray = new Uint8Array(rawData.length)
  
  for (let i = 0; i < rawData.length; i++) {
    outputArray[i] = rawData.charCodeAt(i)
  }
  return outputArray
}


const subscribeToPushes = async () => {
  const registration = await navigator.serviceWorker.ready
  // Use the PushManager to get the user's subscription to the push service.
  let subscription = await registration.pushManager.getSubscription()
  // If a subscription was not found, create a new one
  if (!subscription) {
    // Get the server's public key
    /* const response = await fetch('./vapidPublicKey')
    const vapidPublicKey = await response.text() */
    const vapidPublicKey = 'BCpZ5q5zq1r5X0Q8zq1r5X0Q8zq1r5X0Q8zq1r5X0Q8zq1r5X0Q8zq1r5X0Q8zq'
    // Chrome doesn't accept the base64-encoded (string) vapidPublicKey yet
    // urlBase64ToUint8Array() is defined in /tools.js
    const convertedVapidKey = urlBase64ToUint8Array(vapidPublicKey)
    
    // Otherwise, subscribe the user (userVisibleOnly allows to specify that we don't plan to
    // send notifications that don't have a visible effect for the user).
    subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: convertedVapidKey,
    })
  }
  
  // Send the subscription details to the server using the Fetch API.
  fetch('./register', {
    method: 'post',
    headers: {
      'Content-type': 'application/json',
    },
    body: JSON.stringify({
      subscription: subscription,
    }),
  })
  
  /* document.getElementById('doIt').onclick = function () {
    // Ask the server to send the client a notification (for testing purposes, in actual
    // applications the push notification is likely going to be generated by some event
    // in the server).
    fetch('./sendNotification', {
      method: 'post',
      headers: {
        'Content-type': 'application/json',
      },
      body: JSON.stringify({
        subscription: subscription,
      }),
    })
  } */
}
//ff()
