/// <reference lib="webworker"/>

import { asMsgFromSw, SwMsg } from '@util/service-worker/SwU.ts'
import { asMsgFromWs, WsMsg } from '@util/web-socket/WsU.ts'
import { Env } from '@util/app/Env'
import { AsyncU } from '@util/common/AsyncU.ts'
import { WorkboxPlugin } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  precache,
  addRoute,
  cleanupOutdatedCaches,
} from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import delay = AsyncU.delay
import { WebSocketEx } from '@util/web-socket/WebSocketEx'

import { MockData } from 'src/_mock-data/MockData.ts'
import cross from '@ic/normal/ui/cross.svg'



// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.



declare const self: ServiceWorkerGlobalScope



// self.__WB_MANIFEST contains precached entries that are assets generated by build process.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching.
const selfWorkboxManifest = self.__WB_MANIFEST

console.log('SW selfWorkboxManifest (list of precached entries):', selfWorkboxManifest)


// Precache all the assets generated by your build process.
// Precaching must be first route.
precacheAndRoute(selfWorkboxManifest)
// Clear old precached entries
cleanupOutdatedCaches()




// any query+hash (all content after first '?' (greedy match mode))
//const anyQueryAndHash = /\?.*/
// path that has any file extension in the last path segment
//const anyFileExt = /\/[^\/?]*\.[^\/?]+/




if (!Env.isDev) {
  // Set up App Shell-style routing, so that all navigation requests
  // are fulfilled with your index.html shell.
  // It allows processing route requests via index.html via react-router via SW.
  registerRoute(new NavigationRoute(createHandlerBoundToURL(`${Env.baseUrl}index.html`)))
}



// Workbox strategies:
// https://developer.chrome.com/docs/workbox/modules/workbox-strategies

{
  // Images cache
  const imgExtsList = ['webp', 'svg', 'heic', 'heif', 'jpeg', 'jpg', 'png', 'gif', 'bmp']
  const imgExtsPattern = new RegExp(`[.](${imgExtsList.join('|')})$`, 'i')
  registerRoute(
    // Add in any other file extensions or routing criteria as needed.
    ({ url }) => {
      /*
      console.log('url.pathname', url.pathname)
      console.log('url.pathname is image', imgExtsPattern.test(url.pathname))
      console.log('url.origin', url.origin)
      console.log('self.location.origin', self.location.origin)
      console.log('url.origin === self.location.origin', url.origin === self.location.origin)
       */
      //if (url.origin !== self.location.origin) return false
      
      if (Env.isDev) return false
      
      return imgExtsPattern.test(url.pathname)
    },
    // You can use different cache strategies: new StaleWhileRevalidate(), new CacheFirst(), ...
    new CacheFirst({
      cacheName: 'images',
      plugins: [new ExpirationPlugin({ maxEntries: 300 })] as WorkboxPlugin[],
    })
  )
}




let manifest = (() => {
  /* eslint-disable @stylistic/quotes, @stylistic/comma-dangle */
  const m = {
    "start_url": ".",
    "display": "standalone",
    "orientation": "portrait",
    "theme_color": "#282c34",
    "background_color": "#282c34",
    "icons": [
      {
        "src": `public/res/icon192.png`,
        "type": "image/png",
        "sizes": "192x192"
      },
      {
        "src": `public/res/icon512.png`,
        "type": "image/png",
        "sizes": "512x512"
      },
    ]
  } as const
  /* eslint-enable @stylistic/quotes, @stylistic/comma-dangle */
  return m as Record<string, any> & typeof m
})()

// Intercept & generate dynamic manifest.json
registerRoute(
  ({ url }) => url.pathname === `${Env.baseUrl}manifest.json`,
  async ({ event, request, url, params }) => {
    //console.log('request,url', request,url)
    
    
    const defaultLang = 'en-US'
    const localizationMap = {
      'en-US': {
        lang: 'en-US',
        short_name: 'Kupidon',
        name: 'Kupidon - date app',
        // eslint-disable-next-line @stylistic/max-len
        description: 'Kupidon is a dating and relationship app. We offer users a selection of date ideas and places to make their meetings unforgettable.',
      },
      'ru-RU': {
        lang: 'ru-RU',
        short_name: 'Купидон',
        name: 'Купидон - приложение для свиданий',
        // eslint-disable-next-line @stylistic/max-len
        description: 'Купидон — это приложение для знакомств и укрепления отношений. Мы предлагаем пользователям подборки идей и мест для свиданий, чтобы сделать их встречи незабываемыми.',
      },
    }
    manifest = { ...manifest, ...localizationMap[defaultLang] }
    
    
    const searchParams = url.searchParams
    
    const baseId = 'kupidon-react-pwa'
    const nodeEnvMap = {
      development: {
        id: `${baseId}-dev`,
      },
      production: {
        id: `${baseId}-prod`,
      },
    }
    
    
    const nodeEnv = searchParams.get('nodeEnv')
    if (nodeEnv && nodeEnv in nodeEnvMap) manifest = { ...manifest, ...nodeEnvMap[nodeEnv] }
    
    const lang = searchParams.get('lang')
    if (lang && lang in localizationMap) manifest = { ...manifest, ...localizationMap[lang] }
    
    if (nodeEnv === 'development') {
      manifest.short_name = `Dev ${manifest.short_name}`
      manifest.name = `Dev ${manifest.name}`
      manifest.description = `Dev ${manifest.description}`
    }
    
    
    return new Response(
      JSON.stringify(manifest), {
        headers: {
          //'Content-Type': 'application/manifest+json',
          'Content-Type': 'application/json',
        },
      }
    )
  }
)





const sendMsgFromSw = async (msg: SwMsg) => {
  const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true })
  for (const client of clients) client.postMessage(asMsgFromSw(msg))
}
const sendMsgFromWs = (msg: WsMsg) => sendMsgFromSw(asMsgFromWs(msg))




const ws = new WebSocketEx(`${Env.backendWssHostPort}/ws`)
ws.onmessage = ev => {
  //console.log('WS received:', ev)
  const { type, data } = ev
  if (type === 'TO_CLIENT') {
    sendMsgFromWs(data as WsMsg)
  }
}


type NotificationData = { type: string, data?: any }


const showTestNotification = async (data?: NotificationData) => {
  // Retrieve a list of the clients of this service worker.
  const clients = await self.clients.matchAll({ type: 'window' })
  // Check if there's at least one focused client.
  const focused = clients.some(it => it.focused)
  
  // Show a notification with title and body depending
  // on the state of the clients of the service worker:
  // 1) the page is focused
  // 2) the page is still open but unfocused
  // 3) the page is closed.
  // https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification
  
  const type = (() => {
    if (focused) return 'test--page-focused'
    if (clients.length) return `test--page-hidden`
    return `test--page-closed`
  })()
  const icon = (manifest.icons.find(it => it.sizes === '192x192') ?? manifest.icons[0])?.src
  const dataData = data ?? 1
  
  
  return self.registration.showNotification(
    // Chrome Android: The title of notification shown above body content.
    // Safari iOS: The title of notification shown in the top of notification.
    'Купидон - тестовое уведомление',
    {
      // ✅ Chrome Android: Clone of the data can be read later in event handlers.
      // ✅ Safari iOS: Clone of the data can be read later in event handlers.
      data: { type: type, data: dataData },
      // ✅ Chrome Android: Shows new or updates existing notification with the same tag.
      // ❌ Safari iOS: No support. Always shows new notification.
      tag: type,
      // ✅ Chrome Android: Timestamp associated with the notification. Can be past or future.
      //     Displayed in top-left corner of notification.
      // ❌ Safari iOS: No support.
      // @ts-ignore
      timestamp: +new Date() + 2 * 60 * 1000,
      // Function: Notification can't be closed automatically.
      // ❌??? Chrome Android: Notification was closed after night.
      // ❌??? Safari iOS: Unknown.
      requireInteraction: true,
      // ✅ Chrome Android: true => no sound, no vibration
      // ✅??? Safari iOS: true => no vibration. sound???
      silent: false,
      // ℹ️??? Chrome Android: I see standard vibration instead of provided pattern.
      // ❌ Safari iOS: No support.
      vibrate: [300, 300, 300, 300, 300],
      // ✅ Chrome Android: true => renotify on notification update by same tag.
      // ❌ Safari iOS: No support.
      // @ts-ignore
      renotify: false,
      // ✅ Chrome Android: Specify lang, used in notification. But for what?
      // ℹ️??? Safari iOS: ???
      lang: 'ru-RU',
      // ✅ Chrome Android: Shows icon in the status bar / top-left corner of notification.
      //     Svg supported.
      // ❌??? Safari iOS: No support.
      badge: icon,
      // ✅ Chrome Android: Shows icon in the right of the notification. Svg supported.
      // ❌ Safari iOS: No support. It just displays app icon on the left of notification.
      icon: icon,
      // ✅ Chrome Android: Notification body text.
      // ✅ Safari iOS: Notification body text.
      body: `#${dataData} ` + (() => {
        if (focused) return `Приложение открыто`
        if (clients.length) return `Приложение свёрнуто, нажмите чтобы открыть приложение`
        return `Приложение закрыто, нажмите чтобы открыть приложение`
      })(),
      // ✅ Chrome Android: Shows image under body text. Svg supported.
      // ❌ Safari iOS: No support.
      image: MockData.images.record.blueLockIsagi,
      // ✅ Chrome Android: Experimental: List of action buttons in the bottom of notification.
      // ❌ Safari iOS: No support.
      // @ts-ignore
      actions: [
        // icon: ℹ️ Chrome Android: Пока не увидел иконок в своих оболочках.
        // icon: ❌ Safari iOS: No support.
        // icon: ✅ Chrome Windows: Supported + Svg supported.
        { action: 'delay-for-5s', title: 'Отложить на 5с' },
        { action: 'close', title: 'Закрыть', icon: cross },
      ],
    }
  )
}

// Register event listener for the 'notificationclick' event.
self.addEventListener('notificationclick', ev => ev.waitUntil((async () => {
  console.log('Notification clicked', ev)
  const { action, notification: { data: evData } } = ev
  const { type, data } = evData as NotificationData ?? { }
  if (type.startsWith('test--page')) {
    if (action === 'delay-for-5s') {
      ev.notification.close()
      await delay(5000)
      await showTestNotification(data + 1)
    }
    else if (action === 'close') {
      ev.notification.close()
    }
    else if (!action) {
      ev.notification.close()
      
      //delayAction(5000, () => showTestNotification(data + 1))
      
      // Retrieve a list of the clients of this service worker.
      const clients = await self.clients.matchAll({ type: 'window' })
      
      // If there is at least one client, focus it.
      if (clients.length) return clients[0].focus()
      
      // Otherwise, open a new page.
      return self.clients.openWindow('./')
    }
  }
})()))




self.addEventListener('push', ev => ev.waitUntil((async () => {
  const { type, data } = ev.data?.json() ?? { }
  if (type === 'TEST') {
    await showTestNotification()
  }
})()))




// Service Worker won't be stopped until the Promise passed to 'ev.waitUtil' is settled.
// ev.waitUntil((async () => { ... })()) - tells browser the work is going
//   and that it shouldn't terminate SW until promise is settled.

// ev.ports[0]?.postMessage(<msg>) - send message back if sender has provided the port.

self.onmessage = ev => ev.waitUntil((async () => {
  //console.log('SW received:', ev.data)
  const { type, data } = ev.data ?? { }
  
  if (type === 'TO_WS') {
    ws.send(data)
  }
  else if (type === 'TEST_NOTIFICATION') {
    await showTestNotification()
  }
  else if (type === 'TEST_NOTIFICATION_IN_5S') {
    await delay(5 * 1000)
    await showTestNotification()
  }
  else if (type === 'TEST_NOTIFICATION_IN_1M') {
    await delay(60 * 1000)
    await showTestNotification()
  }
  else {
    if (type === 'KEEP_SW_ALIVE') {
      // Вроде бы держит SW живым несколько минут
      // Можно попробовать создать обычного воркера и перекидываться сообщениями мнжду ними.
      /* await new Promise(async () => {
        while (true) {
          ws.send({ type: `I'M ALIVE` })
          await delay(3000)
        }
      }) */
    }
    else {
      console.log('SW received:', ev.data)
      
      // Used by VitePWA to force 'waiting' SW become 'active' after click on reload button.
      // Trigger skipWaiting via registration.waiting.postMessage({ type: 'SKIP_WAITING' }).
      if (type === 'SKIP_WAITING') {
        self.skipWaiting()
      }
      else if (type === 'CLEAR_CACHE') {
        await clearCache()
        ev.ports[0]?.postMessage({ type: 'CACHE_CLEARED' })
        //self.registration.unregister()
      }
      else if (type === 'CONSOLE_LOG') {
        console.log('service worker console.log', ev)
        ev.ports[0]?.postMessage({ type: 'OK', data: 'logged successfully' })
      }
      else if (type === 'WS_CHECK_READY') {
        sendMsgFromWs({ type: ws.isReady ? 'WS_READY' : 'WS_NOT_READY' })
      }
    }
  }
})())




async function clearCache(): Promise<void> {
  const entryKeys = await caches.keys()
  await Promise.allSettled(entryKeys.map(key => caches.delete(key)))
}



/*
 Worker lifecycle:
 1) Installing.
    This is the first phase after registration.
    When the 'oninstall' handler completes, the service worker is considered 'installed'.
 2) Waiting.
    The service worker is waiting for clients still using other service workers to be closed.
 3) Activating.
    Now there are no clients controlled by other service workers (??? какая-то смутная формулировка).
    When the 'onactive' handler completes, the service worker is considered 'activated'.
 4) Activated
    The service worker now controls the page.
 
 Uncontrolled client - client that does not have any service worker.
 Controlled client - client that already has any service worker.
 
 self.clients.claim() - Start control only uncontrolled clients.
 This does not trigger page reload.
 
 self.skipWaiting() - skips the 'waiting' phase and moves directly to activating.
 Forces controlled pages to update their service worker to this service worker.
 This reloads page.
 */

self.addEventListener('install', ev => ev.waitUntil((async () => {
  if (Env.isDev) ev.waitUntil(self.skipWaiting())
})()))
self.addEventListener('activate', ev => ev.waitUntil((async () => {
  await self.clients.claim()
  await sendMsgFromWs({ type: ws.isReady ? 'WS_READY' : 'WS_NOT_READY' })
})()))

