/// <reference lib="webworker" />

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim, WorkboxPlugin } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  precache,
  addRoute,
  cleanupOutdatedCaches,
} from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { NavigationRouteMatchOptions } from 'workbox-routing/src/NavigationRoute.ts'
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'



declare const self: ServiceWorkerGlobalScope


const isProd = import.meta.env.PROD
const isDev = import.meta.env.DEV
const baseUrl = import.meta.env.BASE_URL // with '/' at the end
const noCache = isDev



// self.__WB_MANIFEST contains precached entries
const selfWbManifest = self.__WB_MANIFEST

console.log('SW selfWbManifest (list of precached)', selfWbManifest)


// Precache all the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching.
precacheAndRoute(selfWbManifest)

// clear old precached entries
cleanupOutdatedCaches()

// '/assets' is autogenerated folder and already precached
// '/public' is already precached
const precachedList = ['/assets/', '/public/']
const precachedPattern = new RegExp(`^(${precachedList.join('|')})`)


// any query+hash (all content after first '?' (greedy match mode))
//const anyQueryAndHash = /\?.*/
// path that has any file extension in the last path segment
//const anyFileExt = /\/[^\/?]*\.[^\/?]+/




// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell.
{
  let navigationRouteMatchOptions: NavigationRouteMatchOptions = {
    // cache all navigation routes
    allowlist: [
      // cache any route
      /.*/,
    ],
    denylist: [precachedPattern],
  }
  
  if (noCache) {
    navigationRouteMatchOptions = { denylist: [/.*/] }
  }
  
  // to allow work offline
  registerRoute(new NavigationRoute(
    createHandlerBoundToURL(baseUrl + 'index.html'),
    navigationRouteMatchOptions,
  ))
}



{
  // Images cache
  const imgExtsList = ['webp', 'svg', 'heic', 'heif', 'jpeg', 'jpg', 'png', 'gif', 'bmp']
  const imgExtsPattern = new RegExp(`\\.(${imgExtsList.join('|')})$`, 'i')
  registerRoute(
    // Add in any other file extensions or routing criteria as needed.
    ({ url }) => {
      /*
      console.log('url.pathname', url.pathname)
      console.log('url.pathname is image', imgExtsPattern.test(url.pathname))
      console.log('url.origin', url.origin)
      console.log('self.location.origin', self.location.origin)
      console.log('url.origin === self.location.origin', url.origin === self.location.origin)
       */
      //if (url.origin !== self.location.origin) return false
      
      if (noCache) return false
      
      if (precachedPattern.test(url.pathname)) return false
      
      return imgExtsPattern.test(url.pathname)
    },
    // Customize this strategy as needed (new StaleWhileRevalidate or new CacheFirst)
    new CacheFirst({
      cacheName: 'images',
      plugins: [
        // Ensure that once this runtime cache reaches a maximum size the
        // least-recently used images are removed.
        new ExpirationPlugin({ maxEntries: 300 }) as WorkboxPlugin,
      ],
    })
  )
}




// manifest.json interceptor & generator
registerRoute(
  ({ url }) => url.pathname === `${baseUrl}manifest.json`,
  async ({ event, request, url, params }) => {
    //console.log('request,url', request,url)
    
    
    const defaultLang = 'en-US'
    const localizationMap = {
      'en-US': {
        lang: 'en-US',
        short_name: 'Kupidon',
        name: 'Kupidon - date app',
        // eslint-disable-next-line @stylistic/max-len
        description: 'Kupidon is a dating and relationship app. We offer users a selection of date ideas and places to make their meetings unforgettable.',
      },
      'ru-RU': {
        lang: 'ru-RU',
        short_name: 'Купидон',
        name: 'Купидон - приложение для свиданий',
        // eslint-disable-next-line @stylistic/max-len
        description: 'Купидон — это приложение для знакомств и укрепления отношений. Мы предлагаем пользователям подборки идей и мест для свиданий, чтобы сделать их встречи незабываемыми.',
      },
    }
    
    /* eslint-disable @stylistic/quotes, @stylistic/comma-dangle */
    let manifest: Record<string, any> = {
      ...localizationMap[defaultLang],
      "start_url": ".",
      "display": "standalone",
      "orientation": "portrait",
      "theme_color": "#282c34",
      "background_color": "#282c34",
      "icons": [
        {
          "src": `public/res/icon192.png`,
          "type": "image/png",
          "sizes": "192x192"
        },
        {
          "src": `public/res/icon512.png`,
          "type": "image/png",
          "sizes": "512x512"
        },
      ]
    }
    /* eslint-enable @stylistic/quotes, @stylistic/comma-dangle */
    
    
    const searchParams = url.searchParams
    
    const baseId = 'kupidon-react-pwa'
    const nodeEnvMap = {
      development: {
        id: `${baseId}-dev`,
      },
      production: {
        id: `${baseId}-prod`,
      },
    }
    
    
    const nodeEnv = searchParams.get('nodeEnv')
    if (nodeEnv && nodeEnv in nodeEnvMap) manifest = { ...manifest, ...nodeEnvMap[nodeEnv] }
    
    const lang = searchParams.get('lang')
    if (lang && lang in localizationMap) manifest = { ...manifest, ...localizationMap[lang] }
    
    if (nodeEnv === 'development') {
      manifest.short_name = `Dev ${manifest.short_name}`
      manifest.name = `Dev ${manifest.name}`
      manifest.description = `Dev ${manifest.description}`
    }
    
    
    return new Response(
      JSON.stringify(manifest),
      {
        headers: {
          'Content-Type': 'application/json',
          //'Content-Type': 'application/manifest+json',
        },
      }
    )
  }
)



/*
 This allows the web app to trigger skipWaiting via
 registration.waiting.postMessage({ type: 'SKIP_WAITING' })
 */
self.addEventListener('message', async ev => {
  const t = ev.data?.type
  // Used by VitePWA to update SW by reload button click
  if (t === 'SKIP_WAITING') {
    void self.skipWaiting()
    clientsClaim()
  }
  else if (t === 'CONSOLE_LOG') {
    console.log('service worker console.log', ev)
  }
  else if (t === 'CLEAR_CACHE') {
    // Service Worker won't be stopped until the Promise passed to 'waitUtil' is settled.
    ev.waitUntil(
      (async() => {
        await clearCache()
        ev.ports[0]?.postMessage({ type: 'CACHE_CLEARED' })
      })()
    )
    //self.registration.unregister()
  }
})




async function clearCache(): Promise<void> {
  const entryKeys = await caches.keys()
  await Promise.allSettled(entryKeys.map(key => caches.delete(key)))
}


// Controlled clients - pages that already being controlled by SW.
// Uncontrolled clients - pages that have no SW worker installed for them.

// If new SW was installed, it can't take control over clients until client page reload.

// It will force reload all controlled clients after SW script was updated.
//void self.skipWaiting()

// clients.claim() will force reload all uncontrolled clients.
// Another variant: self.clients.claim()
//clientsClaim()
