/// <reference lib="webworker"/>

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { WsMsg } from 'src/util/app/WebSocketU.ts'
import { TypeU } from 'src/util/common/TypeU.ts'
import { Env } from 'src/util/app/Env'
import { AsyncU } from 'src/util/common/AsyncU.ts'
import { clientsClaim, WorkboxPlugin } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  precache,
  addRoute,
  cleanupOutdatedCaches,
} from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import delay = AsyncU.delay
import newPromise = AsyncU.newPromise
import isstring = TypeU.isstring



declare const self: ServiceWorkerGlobalScope



// self.__WB_MANIFEST contains precached entries that are assets generated by build process.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching.
const selfWorkboxManifest = self.__WB_MANIFEST

console.log('SW selfWorkboxManifest (list of precached)', selfWorkboxManifest)


// Precache all the assets generated by your build process.
// Precaching must be first route.
precacheAndRoute(selfWorkboxManifest)
// Clear old precached entries
cleanupOutdatedCaches()




// any query+hash (all content after first '?' (greedy match mode))
//const anyQueryAndHash = /\?.*/
// path that has any file extension in the last path segment
//const anyFileExt = /\/[^\/?]*\.[^\/?]+/




if (!Env.isDev) {
  // Set up App Shell-style routing, so that all navigation requests
  // are fulfilled with your index.html shell.
  // It allows processing route requests via index.html via react-router via SW.
  registerRoute(new NavigationRoute(createHandlerBoundToURL(`${Env.baseUrl}index.html`)))
}



// Workbox strategies:
// https://developer.chrome.com/docs/workbox/modules/workbox-strategies

{
  // Images cache
  const imgExtsList = ['webp', 'svg', 'heic', 'heif', 'jpeg', 'jpg', 'png', 'gif', 'bmp']
  const imgExtsPattern = new RegExp(`[.](${imgExtsList.join('|')})$`, 'i')
  registerRoute(
    // Add in any other file extensions or routing criteria as needed.
    ({ url }) => {
      /*
      console.log('url.pathname', url.pathname)
      console.log('url.pathname is image', imgExtsPattern.test(url.pathname))
      console.log('url.origin', url.origin)
      console.log('self.location.origin', self.location.origin)
      console.log('url.origin === self.location.origin', url.origin === self.location.origin)
       */
      //if (url.origin !== self.location.origin) return false
      
      if (Env.isDev) return false
      
      return imgExtsPattern.test(url.pathname)
    },
    // You can use different cache strategies: new StaleWhileRevalidate(), new CacheFirst(), ...
    new CacheFirst({
      cacheName: 'images',
      plugins: [new ExpirationPlugin({ maxEntries: 300 })] as WorkboxPlugin[],
    })
  )
}




// Intercept & generate dynamic manifest.json
registerRoute(
  ({ url }) => url.pathname === `${Env.baseUrl}manifest.json`,
  async ({ event, request, url, params }) => {
    //console.log('request,url', request,url)
    
    
    const defaultLang = 'en-US'
    const localizationMap = {
      'en-US': {
        lang: 'en-US',
        short_name: 'Kupidon',
        name: 'Kupidon - date app',
        // eslint-disable-next-line @stylistic/max-len
        description: 'Kupidon is a dating and relationship app. We offer users a selection of date ideas and places to make their meetings unforgettable.',
      },
      'ru-RU': {
        lang: 'ru-RU',
        short_name: 'Купидон',
        name: 'Купидон - приложение для свиданий',
        // eslint-disable-next-line @stylistic/max-len
        description: 'Купидон — это приложение для знакомств и укрепления отношений. Мы предлагаем пользователям подборки идей и мест для свиданий, чтобы сделать их встречи незабываемыми.',
      },
    }
    
    /* eslint-disable @stylistic/quotes, @stylistic/comma-dangle */
    let manifest: Record<string, any> = {
      ...localizationMap[defaultLang],
      "start_url": ".",
      "display": "standalone",
      "orientation": "portrait",
      "theme_color": "#282c34",
      "background_color": "#282c34",
      "icons": [
        {
          "src": `public/res/icon192.png`,
          "type": "image/png",
          "sizes": "192x192"
        },
        {
          "src": `public/res/icon512.png`,
          "type": "image/png",
          "sizes": "512x512"
        },
      ]
    }
    /* eslint-enable @stylistic/quotes, @stylistic/comma-dangle */
    
    
    const searchParams = url.searchParams
    
    const baseId = 'kupidon-react-pwa'
    const nodeEnvMap = {
      development: {
        id: `${baseId}-dev`,
      },
      production: {
        id: `${baseId}-prod`,
      },
    }
    
    
    const nodeEnv = searchParams.get('nodeEnv')
    if (nodeEnv && nodeEnv in nodeEnvMap) manifest = { ...manifest, ...nodeEnvMap[nodeEnv] }
    
    const lang = searchParams.get('lang')
    if (lang && lang in localizationMap) manifest = { ...manifest, ...localizationMap[lang] }
    
    if (nodeEnv === 'development') {
      manifest.short_name = `Dev ${manifest.short_name}`
      manifest.name = `Dev ${manifest.name}`
      manifest.description = `Dev ${manifest.description}`
    }
    
    
    return new Response(
      JSON.stringify(manifest),
      {
        headers: {
          'Content-Type': 'application/json',
          //'Content-Type': 'application/manifest+json',
        },
      }
    )
  }
)






const swOutChannel = new BroadcastChannel('from-sw')
//swOutChannel.postMessage('SW channel is ready')



class WebSocketEx {
  
  constructor(url: string | URL, protocols?: string | string[]) {
    this.reconnect(url, protocols)
  }
  
  private d: {
    ws?: WebSocket | undefined
    isReady: boolean
  } = {
    isReady: false,
  }
  
  private async reconnect(url: string | URL, protocols?: string | string[]) {
    let attempt = 0
    while (true) {
      this.d.ws = new WebSocket(url, protocols)
      const [whenClosed, setClosed] = newPromise()
      this.d.ws.onopen = () => {
        attempt = 0
        this.updateIsReady()
      }
      this.d.ws.onmessage = ev => this.onmessage?.(ev)
      this.d.ws.onerror = () => {
        // Sending message error
      }
      this.d.ws.onclose = ev => {
        //ev.wasClean
        this.updateIsReady()
        setClosed()
      }
      await whenClosed
      if (attempt <= 40) attempt++
      await delay((() => {
        return 2000 // пока просто 2с оставлю
        
        if (attempt <= 20) return 2000 // 2s
        if (attempt <= 40) return 1 * 60 * 1000 // 1m
        return 10 * 60 * 1000 // 10m
      })())
    }
  }
  
  private updateIsReady() {
    const prevR = this.d.isReady
    const r = this.d.isReady = this.d.ws?.readyState === WebSocket.OPEN
    if (r !== prevR) {
      swOutChannel.postMessage(
        { type: 'FROM_WS', data: { type: r ? 'WS_READY' : 'WS_NOT_READY' } }
      )
    }
  }
  
  
  get isReady() { return this.d.isReady }
  
  sendEv(data: WsMsg) {
    this.updateIsReady()
    if (this.d.ws && this.d.isReady) {
      this.d.ws.send(JSON.stringify(data))
    }
    else {
      swOutChannel.postMessage({ type: 'FROM_WS', data: { type: 'WS_NOT_READY' } })
      throw new Error('WebSocket is not ready')
    }
  }
  
  onmessage: ((ev: MessageEvent) => void) | undefined
  
}



const ws = new WebSocketEx(`${Env.backendWssHostPort}/ws`)






ws.onmessage = ev => {
  //console.log('WebSocket received:', ev.data)
  if (isstring(ev.data)) {
    const { type: t, data } = JSON.parse(ev.data) ?? { }
    if (t === 'TO_CLIENT') {
      swOutChannel.postMessage({ type: 'FROM_WS', data })
    }
  }
}



// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({ type: 'SKIP_WAITING' })
// ev.waitUntil((async () => { ... })()) - tells browser the work is going
//   and that it shouldn't terminate SW until promise is settled.
// ev.ports[0]?.postMessage(<msg>) - send message back if sender has provided the port.
self.onmessage = async ev => {
  console.log('SW received:', ev.data)
  const { type: t, data } = ev.data
  // Used by VitePWA to update SW by reload button click
  if (t === 'SKIP_WAITING') {
    self.skipWaiting()
  }
  else if (t === 'CLEAR_CACHE') {
    // Service Worker won't be stopped until the Promise passed to 'waitUtil' is settled.
    ev.waitUntil((async() => {
      await clearCache()
      ev.ports[0]?.postMessage({ type: 'CACHE_CLEARED' })
    })())
    //self.registration.unregister()
  }
  else if (t === 'CONSOLE_LOG') {
    console.log('service worker console.log', ev)
    ev.ports[0]?.postMessage({ type: 'OK', data: 'logged successfully' })
  }
  else if (t === 'WS_CHECK_READY') {
    swOutChannel.postMessage(
      { type: 'FROM_WS', data: { type: ws.isReady ? 'WS_READY' : 'WS_NOT_READY' } }
    )
  }
  else if (t === 'TO_WS') {
    ws.sendEv(data)
  }
}




self.onactivate = () => {
  //console.log('sw ready')
  //swOutChannel.postMessage({ type: 'SW_READY' })
}



async function clearCache(): Promise<void> {
  const entryKeys = await caches.keys()
  await Promise.allSettled(entryKeys.map(key => caches.delete(key)))
}







// Controlled clients - pages that already being controlled by SW.
// Uncontrolled clients - pages that have no SW worker installed for them.

// If new SW was installed, it can't take control over clients until client page reload,
//   because there is old active SW.
// If page already has SW - self.skipWaiting() reloads pages and applies new SW.
// If page has no SW installed - clientsClaim() reloads such pages and applies SW,
//   but normally page should install SW itself.

// It will FORCE RELOAD all controlled clients after SW script was updated.
if (Env.isDev) self.skipWaiting()

// clients.claim() will FORCE RELOAD all uncontrolled clients and make them controlled.
// !!! Normally page must install SW itself and then self.skipWaiting() is enough
// Another variant: self.clients.claim()
if (Env.isDev) clientsClaim()
